"""Content-Type in documents for displaying documents in frontend

Revision ID: 2b01458b61d9
Revises: 313eaa5a754f
Create Date: 2025-10-18 21:21:08.170255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b01458b61d9'
down_revision: Union[str, Sequence[str], None] = '313eaa5a754f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content_type')
    # ### end Alembic commands ###
