"""minor change removed init from schema of lost and found

Revision ID: 313eaa5a754f
Revises: c7a707c2eb90
Create Date: 2025-10-18 08:07:19.641895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '313eaa5a754f'
down_revision: Union[str, Sequence[str], None] = 'c7a707c2eb90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
