"""Added auto_sync and a new schema for response of moodle tasks

Revision ID: 335ea7068106
Revises: ab1589c3cb0c
Create Date: 2025-09-21 04:55:39.652780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335ea7068106'
down_revision: Union[str, Sequence[str], None] = 'ab1589c3cb0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moodle_accounts', sa.Column('auto_sync', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moodle_accounts', 'auto_sync')
    # ### end Alembic commands ###
