"""Completed Quiz module

Revision ID: 3fea873362e6
Revises: a47da2498162
Create Date: 2025-10-21 15:43:13.445418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fea873362e6'
down_revision: Union[str, Sequence[str], None] = 'a47da2498162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sessions', sa.Column('results_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_sessions', 'results_data')
    # ### end Alembic commands ###
