"""attendace tracker completed

Revision ID: 5fb15c9b4ce6
Revises: 1ccb22bbc487
Create Date: 2025-10-26 09:38:37.192074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fb15c9b4ce6'
down_revision: Union[str, Sequence[str], None] = '1ccb22bbc487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attendance_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('attendance_records_class_instance_id_key'), 'attendance_records', type_='unique')
    op.create_index(op.f('ix_attendance_records_class_instance_id'), 'attendance_records', ['class_instance_id'], unique=True)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.alter_column('class_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('class_instances', 'updated_at')
    op.add_column('schedules', sa.Column('day', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='dayofweek'), nullable=False))
    op.alter_column('schedules', 'time',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_schedule_entry'), 'schedules', type_='unique')
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_index(op.f('ix_schedules_subject_id'), 'schedules', ['subject_id'], unique=False)
    op.drop_column('schedules', 'day_of_week')
    op.alter_column('subjects', 'color',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)
    op.alter_column('subjects', 'total_classes_held',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subjects', 'total_classes_attended',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_user_id'), 'subjects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_user_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.alter_column('subjects', 'total_classes_attended',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subjects', 'total_classes_held',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subjects', 'color',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
    op.add_column('schedules', sa.Column('day_of_week', postgresql.ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='dayofweek'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_schedules_subject_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.create_unique_constraint(op.f('uq_schedule_entry'), 'schedules', ['subject_id', 'day_of_week', 'time'], postgresql_nulls_not_distinct=False)
    op.alter_column('schedules', 'time',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=False)
    op.drop_column('schedules', 'day')
    op.add_column('class_instances', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('class_instances', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_class_instance_id'), table_name='attendance_records')
    op.create_unique_constraint(op.f('attendance_records_class_instance_id_key'), 'attendance_records', ['class_instance_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('attendance_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
