"""Added a column in tasks

Revision ID: 9042807deebe
Revises: 335ea7068106
Create Date: 2025-09-21 06:34:51.147790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9042807deebe'
down_revision: Union[str, Sequence[str], None] = '335ea7068106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moodle_accounts', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('task_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tasks', ['task_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'task_url')
    op.drop_column('moodle_accounts', 'last_synced_at')
    # ### end Alembic commands ###
