"""Implemented Quiz models and schemas.

Revision ID: a47da2498162
Revises: 2b01458b61d9
Create Date: 2025-10-20 13:04:30.961785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47da2498162'
down_revision: Union[str, Sequence[str], None] = '2b01458b61d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_sessions', sa.Column('raw_content', sa.Text(), nullable=True))
    op.alter_column('quiz_sessions', 'document_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_sessions', 'document_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('quiz_sessions', 'raw_content')
    # ### end Alembic commands ###
