"""Added is_moodle bool in tasks

Revision ID: ab1589c3cb0c
Revises: 226cf1fbf87d
Create Date: 2025-09-21 04:15:32.841354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1589c3cb0c'
down_revision: Union[str, Sequence[str], None] = '226cf1fbf87d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_moodle_task', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_moodle_task')
    # ### end Alembic commands ###
