"""Implemented lost and found

Revision ID: c7a707c2eb90
Revises: dfc71d382056
Create Date: 2025-10-18 07:50:00.283014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a707c2eb90'
down_revision: Union[str, Sequence[str], None] = 'dfc71d382056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lost_and_found_items', sa.Column('title', sa.String(), nullable=False))
    op.add_column('lost_and_found_items', sa.Column('item_type', sa.Enum('ELECTRONICS', 'CLOTHING', 'PERSONAL_ITEM', 'BAGS', 'BOOKS', 'JEWELRY', 'KEYS', 'OTHERS', name='lostandfounditemtype'), nullable=True))
    op.add_column('lost_and_found_items', sa.Column('location', sa.String(), nullable=True))
    op.add_column('lost_and_found_items', sa.Column('photo_path', sa.String(), nullable=True))
    op.add_column('lost_and_found_items', sa.Column('reporter_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lost_and_found_items', 'reporter_name')
    op.drop_column('lost_and_found_items', 'photo_path')
    op.drop_column('lost_and_found_items', 'location')
    op.drop_column('lost_and_found_items', 'item_type')
    op.drop_column('lost_and_found_items', 'title')
    # ### end Alembic commands ###
